version: "3.7"

services:
  api:
    volumes:
      - .:/workspace
      - node_modules_volume:/workspace/node_modules
    ports:
      - "4000:4000"
    image: node:16
    networks:
      - y-node-network
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldb:/var/lib/mysql
    networks:
      - y-node-network
  mysql-test:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqltestdb:/var/lib/mysql
    networks:
      - y-node-network
volumes:
  node_modules_volume:
  mysqldb:
  mysqltestdb:

networks:
  y-node-network:
    external: true
